Fix some dwm stuff

diff --git a/bin/bin/patchdir b/bin/bin/patchdir
--- a/bin/bin/patchdir
+++ b/bin/bin/patchdir
@@ -1,15 +1,41 @@
 #!/bin/sh
 
+REVERSE=0
+
+can_apply_patch () {
+    return $(patch -R -p1 -s -f --dry-run -i $1 >/dev/null)
+}
+
+apply_patch () {
+    echo "Applying $1..."
+    patch -s -f -p1 -i "$1"
+    if ! [ $? -eq 0 ]
+    then
+	    echo "Could not apply patch: $1"
+	    exit 1
+	fi
+}
+
+while getopts "r" opt
+do
+	case $opt in
+        r) REVERSE=1 ;;
+	esac
+done
+shift $OPTIND
+
+patchfiles=$(find -L $1 -iname "*.diff" | sort);
+
 if [ $REVERSE -eq 1 ]; then
-patchfiles=$(find -L patches -iname "*.diff" | sort -R);
-else
-patchfiles=$(find -L patches -iname "*.diff");
+	patchfiles=$(echo $patchfiles | sort -R);
 fi
 
-
-for pf in $patchfiles ; do
-    echo "Unpatched $pf"
-    patch -R <"$pf"
+for pf in $patchfiles
+do
+	if can_apply_patch $pf
+	then
+		apply_patch $pf
+	fi
 done
 
 
